Issue #143 Table of Contents
Lednerb/bilberry-hugo-theme pull request #257
Opened 2020-09-20 03:31 UTC by igor-baiborodine

Implementation of the table of contents feature

Test website: https://bilberry-toc-test.netlify.app/

2020-09-21 14:12 UTC, Lednerb requested changes

2020-09-21 14:12 UTC, Lednerb commented on i18n/en.toml
> +other = "Table of Contents"
Does hugo produce a build error if this string is missing?
If so, we need to add the translations for all supported languages so we don't introduce a breaking change here that woud cause a versioning step to version 3 of this theme.

I would like to have it backwards compatible, so users can upgrade the theme without interruptions.

2020-09-22 01:38 UTC, igor-baiborodine commented on assets/sass/_articles.scss
> +            }
I simplified it to this:
`ul {
                &:not(:first-child) {
                    display: list-item;
                    padding-left: 0.9rem;
                    font-size: 95%;
                }
            }`

2020-09-22 01:41 UTC, igor-baiborodine commented on i18n/en.toml
> +other = "Table of Contents"
I piped with `default "tableOfContents' to display the code if a corresponding i18n is not implemented:

`<h2>{{ i18n "tableOfContents" | default "tableOfContents" }}</h2>`

2020-09-22 15:41 UTC, Lednerb requested changes

2020-09-22 15:41 UTC, Lednerb commented on assets/sass/_articles.scss
> +            }
Please combine these blocks into one and I will merge the PR :+1: 

Thanks for your great contribution again!

2020-09-22 21:04 UTC, Lednerb approved these changes

2020-09-22 21:04 UTC, merged