Add documentation on usig theme as module
Lednerb/bilberry-hugo-theme pull request #327
Opened 2022-01-08 17:56 UTC by deining

As requested in #326.

Please let me know if you like it. I proposed using modules as recommended approach, but I'm certainly biased here.
Did you find time to experiment with the Bilberry Sandbox already?

2022-01-11 13:56 UTC, igor-baiborodine commented on README.md
> +```
When I tested, the `exampleSite` folder is excluded from vendoring.

![image](https://user-images.githubusercontent.com/1027701/148954977-14e1f577-4f62-4842-8c94-eb1e6982db6b.png)

Therefore, the copying of the `exampleSite` folder will fail.

I guess it's excluded because it is declared as a module. So to make it work, the `exampleSite` module should be imported also as a separate dependency.

2022-01-11 13:59 UTC, igor-baiborodine commented
I tested migration with the Bilberry Sandbox. It worked well.

https://github.com/igor-baiborodine/bilberry-hugo-theme-sandbox/pull/12

https://deploy-preview-12--bilberry-sandbox.netlify.app/

2022-01-11 15:49 UTC, deining commented on README.md
> +```
> When I tested, the `exampleSite` folder is excluded from vendoring.

I see.

> Therefore, the copying of the `exampleSite` folder will fail.

Of course.

> I guess it's excluded because it is declared as a module.

Yes, that sounds reasonable.

> So to make it work, the `exampleSite` module should be imported also as a separate dependency.

That may work, but sounds a bit strange to me. I would propose, we leave the exampleSite as is and do **not** turn it into a hugo Module, then everything should work as documented by me. Should I make this change in my `module` branch (#326)?

2022-01-11 15:52 UTC, deining commented
> I tested migration with the Bilberry Sandbox. It worked well.

Glad to hear that.

Based on your recent experience, what do you like more: the hugo modules approach or the git submodule installation? Or do you think they are equivalent?

2022-01-11 16:51 UTC, igor-baiborodine commented
> > I tested migration with the Bilberry Sandbox. It worked well.
> 
> Glad to hear that.
> 
> Based on your recent experience, what do you like more: the hugo modules approach or the git submodule installation? Or do you think they are equivalent?

It does not make a big difference, but I need to test the modules approach for the theme development.

2022-01-11 16:55 UTC, igor-baiborodine commented on README.md
> +```
I merged your branch into [bilberry-hugo-theme/module](https://github.com/Lednerb/bilberry-hugo-theme/tree/module) branch. I will make the changes in this branch and test it.

2022-01-12 14:08 UTC, igor-baiborodine commented on README.md
> +```
I was not able to make it work. Using [my fork](https://github.com/igor-baiborodine/bilberry-hugo-theme) with added `go.mod` files and other adjustments, I tried the following:
```shell
hugo mod init github.com/igor-baiborodine/my-new-blog

# add to config.toml
[module]
  [[module.imports]]
    path = "github.com/igor-baiborodine/bilberry-hugo-theme/exampleSite"
    disable = false

hugo mod vendor

cp -r _vendor/github.com/igor-baiborodine/bilberry-hugo-theme/exampleSite/* .

rm archetypes/default.md

hugo serve
```
Then the site is up but the content is not displayed properly.

In my opinion, it takes more work converting the theme to Hugo modules since the current theme's structure does not conform 100% to the predefined Hugo module structure.

2022-01-12 21:25 UTC, deining commented on README.md
> +```
> I was not able to make it work.

I guess I know why.

> In my opinion, it takes more work converting the theme to Hugo modules since the current theme's structure does not conform 100% to the predefined Hugo module structure.

No, I don't think that's correct.

To set up it properly, you should delete `go.mod` of your example site in your fork:

```
rm exampleSite/go.mod
```

This file prevents the folder `exampleSite` from showing up when vendoring the theme module.

After committing that change:

```
hugo new site my-new-blog
cd my-new-blog
hugo mod init github.com/igor-baiborodine/my-new-blog

# add to config.toml
[module]
  [[module.imports]]
    path = "github.com/igor-baiborodine/bilberry-hugo-theme"
    disable = false

hugo mod vendor

cp -r _vendor/github.com/igor-baiborodine/bilberry-hugo-theme/exampleSite/* .

rm archetypes/default.md

hugo serve
```

Then everything should work. That's untested, let me know whether my analysis is correct.

2022-01-13 13:18 UTC, igor-baiborodine requested changes

2022-01-13 13:18 UTC, igor-baiborodine commented on README.md
> +```
No, that didn't work either. Since the `exampleSite` folder is not part of the standard Hugo module structure, it will be excluded. The same goes for the `algolia` folder.

2022-01-13 16:39 UTC, deining commented on README.md
> +```
I tried it out locally and found a elegant way to make it work. You may found valid instructions now in README.md

2022-01-13 16:41 UTC, deining commented
I tried it out locally and found a elegant way to make it work. You will found valid instructions now in README.md.
Thanks for checking it out!

2022-01-15 18:13 UTC, igor-baiborodine commented
Could you please provide me with the commands you used to test instructions in your local dev? Against what fork/branch did you try it?

2022-01-15 19:44 UTC, deining commented
> Could you please provide me with the commands you used to test instructions in your local dev? Against what fork/branch did you try it?

That's how it works (tested):

```
hugo new site billberry-test
cd billberry-test/
hugo mod init billberry-test
hugo mod get github.com/Lednerb/bilberry-hugo-theme
```

- Add to your `config.toml`:

```
[module]
  [[module.imports]]
    path = "github.com/Lednerb/bilberry-hugo-theme"
    disable = false
  [[module.imports.mounts]]
    source = "exampleSite"
    target = "assets/exampleSite"
```

At the command line:

```
hugo mod vendor
cp -r _vendor/github.com/Lednerb/bilberry-hugo-theme/exampleSite/* .
rm -rf _vendor/
```

At the top of your copied config.toml, activate theme as module:

```
# using theme as Hugo module
[[module.imports]]
path = "github.com/Lednerb/bilberry-hugo-theme"
```

At the command line again:

```
hugo serve
```

Site is up and running!
Thanks for testing it out!

2022-01-16 21:51 UTC, igor-baiborodine requested changes
It worked, but I question the necessity of turning the `exampleSite` folder into a module. Also, the `hugo mod get` can be skipped.

2022-01-16 21:51 UTC, igor-baiborodine commented on exampleSite/go.mod
> +
Is it necessary to turn the exampleSite folder into a module? I think it should work without turning it into a module.

2022-01-16 21:51 UTC, igor-baiborodine commented on README.md
> +hugo mod get github.com/Lednerb/bilberry-hugo-theme
No need to use the `hugo mod get` command. The `hugo mod vendor` command will download the necessary modules.
![image](https://user-images.githubusercontent.com/1027701/149679406-e57be1cd-3b67-43df-a5bc-947bcec513b9.png)

2022-01-16 22:50 UTC, deining commented on exampleSite/go.mod
> +
> Is it necessary to turn the exampleSite folder into a module?

No, it isn't.

That's the reason why I turned the `exampleSite` folder into a module: Currently you have to run:

```
hugo server --themesDir ../..
``` 

Once we turn it into a module, this command will be sufficient:

```
hugo server
```

But I can revert the change of the exampleSite to a module, if you want.

2022-01-16 22:53 UTC, deining commented on README.md
> +hugo mod get github.com/Lednerb/bilberry-hugo-theme
> No need to use the `hugo mod get` command.

Correct. It doesn't do any harm either.

The reason why I put it in is to make the process more transparent to the user.

But we can omit this extra step if you want. Please advice what to do.

2022-01-16 23:24 UTC, igor-baiborodine requested changes

2022-01-16 23:24 UTC, igor-baiborodine commented on README.md
> +hugo mod get github.com/Lednerb/bilberry-hugo-theme
Perfect. Let's keep it explicit.

2022-01-16 23:24 UTC, igor-baiborodine commented on exampleSite/go.mod
> +
Okay, let's keep the exampleSite as a module. But for nested modules, the module's name should match the actual path. Therefore, I suggest changing it to `module github.com/Lednerb/billberry-hugo-theme/exampleSite`.

2022-01-17 00:31 UTC, deining commented on exampleSite/go.mod
> +
> Therefore, I suggest changing it to `module github.com/Lednerb/billberry-hugo-theme/exampleSite`.

You are right. I changed the module name as requested.

2022-01-17 12:57 UTC, igor-baiborodine approved these changes

2022-01-17 12:57 UTC, igor-baiborodine commented
@deining, thanks for your contribution.

2022-01-17 12:58 UTC, merged