feat: implementation of dark theme
Lednerb/bilberry-hugo-theme pull request #605
Opened 2023-10-22 10:13 UTC by atsuyaw

Resolve #185, #315, #525, #526.

Feel free posting any comments including on the default color scheme ;)

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/68371029/d31dc5fc-931a-4bc9-b582-733df5b847df)

2023-10-22 18:25 UTC, igor-baiborodine commented
@atsuyaw, thank you very much! It's a big pull request and will take me time to review.

2023-10-29 21:18 UTC, igor-baiborodine requested changes
There should not be duplicated `_dk-*.scss` files. The only new SCSS file should be `dark-theme.css` which is a copy of `theme.css` but with different values for customizable variables.

2023-10-29 21:18 UTC, igor-baiborodine commented on v4/layouts/partials/css.html
> +
I want to suggest updating as follows:
```html
{{ $options := dict "targetPath" "theme.css" "enableSourceMap" true "precision" 6 }}
{{ $css := resources.Get "sass/theme.scss" | resources.ExecuteAsTemplate "theme.scss" . | toCSS $options }}

{{ if isset .Site.Params "enableLightDarkMode" }}
    {{ $darkOptions := dict "targetPath" "dark-theme.css" "enableSourceMap" true "precision" 6 }}
    {{ $darkCss := resources.Get "sass/dark-theme.scss" | resources.ExecuteAsTemplate "dark-theme.scss" . | toCSS $dark-options }}
{{ end }}

{{ if or (.Site.IsServer) (eq hugo.Environment "development") }}
    <link rel="stylesheet" href="{{ $css.Permalink }}" media="screen">
    {{ if $darkCss }}
    <link disabled id="dark-theme-css" rel="stylesheet" href="{{ $darkCss.Permalink }}" media="screen">
    {{ end }}
{{ else }}
    {{ $css := $css | resources.Minify | resources.Fingerprint }}
    <link rel="stylesheet" href="{{ $css.Permalink }}" integrity="{{ $css.Data.Integrity }}" media="screen">
    {{ if $darkCss }}
    {{ $darkCss := $darkCss | resources.Minify | resources.Fingerprint }}
    <link disabled id="dark-theme-css" rel="stylesheet" href="{{ $darkCss.Permalink }}" integrity="{{ $css.Data.Integrity }}" media="screen">
    {{ end }}
{{ end }}

{{ if isset .Site.Params "css_modules" }}
    {{ range .Site.Params.css_modules }}
        <link rel="stylesheet" href="{{ . | absURL }}">
    {{ end }}
{{ end }}
```

2023-10-31 04:06 UTC, atsuyaw commented on v4/layouts/partials/css.html
> +
Thanks, but hugo cannot process your code.
I tried the following with a small modification, but the mode selector doesn't work correctly due to `dark-theme.css` be not loaded.
Do you have any idea?
```sass
{{ $options := dict "targetPath" "theme.css" "enableSourceMap" true "precision" 6 }}
{{ $css := resources.Get "sass/theme.scss" | resources.ExecuteAsTemplate "theme.scss" . | toCSS $options }}
{{ $darkCss := "" }}

{{ if .Site.Params.enableLightDarkMode }}
    {{ $darkOptions := dict "targetPath" "dark-theme.css" "enableSourceMap" true "precision" 6 }}
    {{ $darkCss := resources.Get "sass/dark-theme.scss" | resources.ExecuteAsTemplate "dark-theme.scss" . | toCSS $darkOptions }}
{{ end }}

{{ if or (.Site.IsServer) (eq hugo.Environment "development") }}
    <link rel="stylesheet" href="{{ $css.Permalink }}" media="screen">
    {{ if $darkCss }}
    <link disabled id="dark-theme-css" rel="stylesheet" href="{{ $darkCss.Permalink }}" media="screen">
    {{ end }}
{{ else }}
    {{ $css := $css | resources.Minify | resources.Fingerprint }}
    <link rel="stylesheet" href="{{ $css.Permalink }}" integrity="{{ $css.Data.Integrity }}" media="screen">
    {{ if $darkCss }}
    {{ $darkCss := $darkCss | resources.Minify | resources.Fingerprint }}
    <link disabled id="dark-theme-css" rel="stylesheet" href="{{ $darkCss.Permalink }}" integrity="{{ $darkCss.Data.Integrity }}" media="screen">
    {{ end }}
{{ end }}

{{ if isset .Site.Params "css_modules" }}
    {{ range .Site.Params.css_modules }}
        <link rel="stylesheet" href="{{ . | absURL }}">
    {{ end }}
{{ end }}
```

Removing`{{ if .Site.Params.enableLightDarkMode }}` and the corresponding `{{ end }}`, this code works.

2023-10-31 04:29 UTC, atsuyaw commented on v4/layouts/partials/css.html
> +
Ah, `theme.js` always needs `dark-theme.css`. So, it's difficult to accept this request.

2023-11-03 04:05 UTC, atsuyaw commented
Thanks for helping!
Let me try to "polish" the colors prior to merging.

2023-11-03 07:45 UTC, atsuyaw commented
@igor-baiborodine Now I made a modification on the colors. Would you check again?
Thank you!

2023-11-05 19:52 UTC, igor-baiborodine commented
@atsuyaw, here is the Bilberry Sandbox deployed using your branch. You can compare it with the Bilberry Sandbox deployed using the latest release.
* https://deploy-preview-45--bilberry-sandbox.netlify.app/
* https://www.bilberry-sandbox.kiroule.com/
The light mode should be tested for regression. Here I spotted the first one: the line connecting the post icons. Also, the theme mode selection is not saved, and going to a different page with the dark mode selected defaults to the light mode.

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/1027701/9f33cfb8-69c8-46b4-94a7-7856c97c4fe8)

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/1027701/d29f8273-7898-41a7-a7a5-3f1d03140a3e)

2023-11-05 19:55 UTC, igor-baiborodine requested changes
@atsuyaw, please see my comment above.

2023-11-06 13:53 UTC, Lednerb commented
Hello all,

thanks for your great work!

The colors are OK for me in general, but I think some adjustments should be added:

![grafik](https://github.com/Lednerb/bilberry-hugo-theme/assets/2056876/030b3682-5980-4ad0-8d9d-bff75ca08311)

1: The lighter color coming from above will add some more contrast
2: I think the meta line should also have a bit more contrast, like the font in the article footer
3: The background is too bright, maybe more like GitHub `inline code` in the dark mode?


![grafik](https://github.com/Lednerb/bilberry-hugo-theme/assets/2056876/9d32e7bd-042c-4878-8bcc-06df5807aee5)

Additionally the search box should also be adjusted before the final merge.

And hover states on links are not readable:
![grafik](https://github.com/Lednerb/bilberry-hugo-theme/assets/2056876/fcd84639-6038-49d3-9261-3c02d8f04078)



----

The color theme switcher is very neat!

2023-11-07 13:29 UTC, igor-baiborodine commented on v4/layouts/partials/css.html
>  {{ $options := dict "targetPath" "theme.css" "enableSourceMap" true "precision" 6 }}
No, usually when you run your site in local dev, i.e., in `development` mode, the final CSS shouldn't be minified and fingerprinted.

2023-11-13 22:59 UTC, igor-baiborodine commented
@atsuyaw, the Bilberry Sandox was updated with your latest commits. The only issue I see now is the flickering that happens when changing pages in the dark mode.

[Screencast from 2023-11-13 05:53:09 PM.webm](https://github.com/Lednerb/bilberry-hugo-theme/assets/1027701/9f580350-2bf3-498d-9f8b-74482829190d)

2023-11-13 23:04 UTC, igor-baiborodine commented on v4/assets/sass/_articles.scss
> +        border-right-color: $con-line-colorB;
Can the variable name be more descriptive? `con` is it for connection? `colorB` -> color-before.
The same goes for `con-line-colorA`.

2023-11-14 00:25 UTC, atsuyaw commented
@igor-baiborodine,
Thanks for your cooperation and pointing out!
I need to modify also the giscus theme behavior with the global dark mode.

2023-11-14 22:08 UTC, igor-baiborodine commented on v4/assets/sass/dark-theme.scss
> +* {
I don't think it's necessary to override the scrollbar provided by the browser. Let's keep the default one.

2023-11-19 20:16 UTC, igor-baiborodine requested changes
The connection line should be of the same color, i.e., the same as in the part. 

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/1027701/7a1e9836-be4c-4875-8450-99841cbb2708)

There is still the issue of flickering when using the Chrome browser. In Firefox, it works fine.

2023-11-19 20:16 UTC, igor-baiborodine commented on v4/README.md
> +  enableLightDarkThemeMode = true
Should be `enableLightDarkTheme`.

2023-11-26 07:04 UTC, atsuyaw commented
Here, the switching mechanism has been reconstructed.
Please try to check the improvement; the Network throttling mode in inspecting tools of Chrome was useful in my cording.

2023-11-29 21:53 UTC, igor-baiborodine reviewed
I updated the sandbox, and there is no flickering, but it's going back to the light mode when I change a page after selecting the dark mode.

https://deploy-preview-45--bilberry-sandbox.netlify.app/

2023-12-01 01:59 UTC, atsuyaw commented on v4/layouts/partials/check-theme-prefer.html
> +{{ $checkThemePrefer := slice $jsToConcat | resources.Concat "check-theme-prefer.js" }}
Thanks, I applied this!

2023-12-05 13:48 UTC, igor-baiborodine reviewed
I updated the Sandbox, and everything works fine, but there is a minor issue with showing `js/check-theme-prefer.js` in the top left corner.

https://deploy-preview-45--bilberry-sandbox.netlify.app/

![image](https://github.com/Lednerb/bilberry-hugo-theme/assets/1027701/f0d40602-2bdd-4daa-b607-55dd003c5087)

2023-12-06 11:36 UTC, atsuyaw reviewed
Huuum, i saw it on the sandbox, however this issue wasn't observed in my local environment. Now i'm trying fix this line.
Let me check on the sandbox. I am sorry for inconvenience...!

2023-12-06 14:20 UTC, igor-baiborodine approved these changes
@atsuyaw, great job! Thank you!

2023-12-06 14:22 UTC, merged